# ===========================================================
# Accelerate configuration for 2x A6000 GPUs (single node)
# ===========================================================
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
num_processes: 2
num_machines: 1
machine_rank: 0
same_network: true

# This must be open and consistent across all processes
main_process_port: 29500
main_process_ip: null

# Mixed precision settings
mixed_precision: bf16

# Logging and performance
dynamo_backend: "NO"
fsdp_config: {}
use_cpu: false

# Ensure main process logs output, others stay quiet
debug: false
downcast_bf16: no